### ISSUE TITLE
Metadata on where tags begin and end

### ISSUE THREAD

**Issue by brettz9** [syavorsky/comment-parser#106]
Hi,

I'm testing out v1.0, and getting some feel for the API and appreciate being able to see it meet a good number of our prior needs, and is exciting to have the promise of using it for additional needs.

However, one challenge currently is that I see it, a big part of the appeal of a stringifier is being able to work with individually parsed tags and modify info about those tags, e.g., to remove a type, to change the optionality, etc.

If one is introspecting on a tag, (`Spec`), it is not helpful for stringification purposes to modify `Spec`'s direct children like `type` or `optional` there as would be nice. One can at least reach into the `source[].tokens` on `tags` and modify the properties of `tokens` (such as an individual token `type`), albeit with a little bit of minor checking or parsing (e.g., adding or removing `[` and `]` for a name).

However, while one can iterate and modify `tags[].source[].tokens` until reaching the end or `end` , and then stringify  and join each of the modified`tags[].source.tokens`, this will not include the jsdoc block opening (such as `/**` and any leading  description), and there is nothing on `Block` (or on `tags[0]`) to conveniently allow one to determine how many of the initial `Block`'s `source[].tokens` also need to be stringified without having to reiterate through each `source[].tokens.tag` until stopping right before the first non-empty one.

Likewise, one also can't find all possible ending non-tag descriptions or final`end` (`*/`) within `tags` either.

I am thinking one small change that would be very helpful would be if `Block` could indicate the array index of its `source` at which `tags` begins and ends, this could avoid being forced to do all modifications on the `source` of `Block`.

Is this something you'd be open to making available?

With `Block.tagStart` and `Block.tagEnd`, the process could therefore become:

1. Iterate and modify `Block.tags[].source[].tokens` as needed
2. Stringify and join the following pseudo-code `[Block.source.slice(0, Block.tagStart), ...tags[].source[].tokens, Block.source.slice(Block.tagEnd + 1)]`

**Comment by syavorsky** [comment]
Correct me if I miss the point. Your concern is that `Block.tags[].source` may diverge from `Block.source`. This is true, and I indeed was considering storing only Spec's start/end indices pointing to the source. This approach would solve some problems while introducing others, think about dropping or re-ordering lines.

Let me defend the chosen approach by explaining it different way. Let's accept that the `Block.source` is a source of truth and `Block.tags[].source` is just a view/slice of it, despite JS has neither of those concepts. By saying "view" I mean it is an Array of references to `Block.source` items, not copies. So, to iterate over the corresponding portion of `Block.source` you just iterate over its representation in `Block.tags[].source`. It's not ideal, as you pointed out things could easily go wrong, but I couldn't think of much better alternative. 

Best workaround I have so far is a helper [rewiring](https://github.com/syavorsky/comment-parser/blob/master/src/util.ts#L58-L67) Spec's source. You can see it is used in all bundled transforms [1](https://github.com/syavorsky/comment-parser/blob/master/src/transforms/align.ts#L80), [2](https://github.com/syavorsky/comment-parser/blob/master/src/transforms/indent.ts#L27), and checked in corresponding unit tests [1](https://github.com/syavorsky/comment-parser/blob/master/tests/unit/transforms-align.spec.ts#L62), [2](https://github.com/syavorsky/comment-parser/blob/master/tests/unit/transforms-indent.spec.ts#L84)

**Comment by brettz9** [comment]
It is convenient for us to use `Block.tags[].source` for *reading* as that is at least broken up by tag.

So, to take "block with tags" in `tests/unit/parser.spec.ts` as an example:

```js
/**
   * Description may go 
   * over few lines followed by @tags
   * @param {string} name name parameter
   *
   * @param {any} value value of any type
   */
```

Let's say we want to remove all param types.

I can iterate `Block.tags[].source`, remove `type` and `postType` and then stringify this `source`, but that will only give me:

 ```
   * @param {string} name name parameter
   *
   * @param {any} value value of any type
   */ ```

(Actually I'm not sure why `Block.tags[].source` sometimes has the ending and sometimes doesn't, but I can check for the presence of `end` to know if I'm done.)

The problem is that in order to stringify the portions of `Block.source` so as to get this:

```
/**
   * Description may go 
   * over few lines followed by @tags
```

...I don't have an easy way to figure out where to stop slicing from the beginning of `Block.source` (or the end for those times when `tags` doesn't include the ending). This info is only in `Block.source`, but I can't use info in `Block.tags[]` to know which parts of `Block.source` I haven't yet handled.

**Comment by syavorsky** [comment]
I see, tell me if this works. You can get non-tag lines stringified by iterating over entire `Block.source` instead of each tag individually, since both are representing same items

if you are the end consumer of parsed block then you can just update it in-place
```js
const { parse, stringify } = require('./lib');

const block = parse(`
  /**
   * Description may go
   * over multiple lines followed by @tags
   * @param {string} name the name parameter
   * @param {any} value the value parameter
   */`)[0];

block.tags.forEach((spec) =>
  spec.source.forEach(({ tokens }) => {
    tokens.type = '';
    tokens.postType = '';
  })
);

console.log(stringify(block));
```

Alternatively, you can do whatever you like to tags, and sync them back to the block source
```js
const { parse, stringify } = require('./lib');

const  block = parse(`
  /**
   * Description may go
   * over multiple lines followed by @tags
   * @param {string} name the name parameter
   * @param {any} value the value parameter
   */`)[0];

const clonned = rewireSpecs({
  ...block,
  tags: block.tags.map((tag) => ({
    ...tag,
    source: tag.source.map((line) => ({
      ...line,
      tokens: { ...line.tokens, type: '', postType: '' },
    })),
  })),
});

console.log(stringify(block));
```
both would produce same output
```
  /**
   * Description may go
   * over multiple lines followed by @tags
   * @param name the name parameter
   * @param value the value parameter
   */
```

**Comment by syavorsky** [comment]
As for dangling `*/`, this might really be better but I couldn't come up with the right strategy. 

Currently, `parser/block-parser.ts` is splitting the source into `Line[][]` chunks like `[description, tag0, ..., tagX]`, this might be something like `[description, tag0, ..., tagX, tail-lines]`. But then I can't clearly answer how to split the `tail-lines` for the follwoing

```
  /**
   * Description may go
   * over multiple lines followed by @tags
   * @param name the name parameter
   * @param value the value parameter
   *
   */
```
should the `tail-lines` include two ending lines or just last one? I can't tell if those empty lines are the white-space belonging to the last tag's description or something else. So tag's `Line[][]` source portion counts everything up to the next tag or to the block end.

**Comment by syavorsky** [comment]
published `comment-parser@1.0.1` providing `rewireSpecs`

**Comment by brettz9** [comment]
While I haven't benchmarked it, my concern would be that this doesn't seem very optimal for stringification as the approach requires multiple runs through the data (once on `tags[].source` and once on ``Block.source`), as I would indeed need to rewire it. With our eslint plugin running potentially frequently, e.g., in an IDE, it's not something I'd imagine would be helpful in eating up extra resources, though I haven't gotten to benchmarking it.

I guess I don't see, at least for our uses, the value of having separate locations for tokens (outside of simplifying the stringifier slightly).

Do you or your users really need all of `Block.source` or could its non-tag tokens instead be kept on a property like `Block.opening` and `Block.end` and let users also iterate within `tags` if they want the full source? That would avoid footguns for the user too with potentially out of sync data, and they wouldn't need to rewire anything.

If that's what you need, I understand, but it seems less than ideal for our use case.

**Comment by syavorsky** [comment]
Again, if you are not concerned changing source in-place, there are no performance implications. For most of the cases yoy would not need copying indeed

**Comment by brettz9** [comment]
Yeah, I guess you're right, fixing wouldn't be as frequent at all... Ok, I think I can manage--thanks, and thanks for the rewire utility!

**Comment by brettz9** [comment]
Seems to be working well so far, thanks... But I think you must have meant to flip the names `rewireSpecs` and `rewireSource` since the former is changing the specs and the later is changing the main source (the code comments for what is currently `rewireSpecs` also seem mistaken).

**Comment by brettz9** [comment]
One limitation that might be mentioned too is that I believe this only works when sources (of either type) are not added or removed (e.g., if one adds a source to a tag, it won't be reflected in `Block.source`).

**Comment by syavorsky** [comment]
Good point, I will take care of added/removed lines

**Comment by brettz9** [comment]
Btw, I've released a new version of `eslint-plugin-jsdoc` which incorporates 1.0.1, and it looks like it will work nicely. An improved rewiring utility might help simplify some of our calling code, but there seem to be no noticeable changes after running some benchmarking against a large project. Thanks again for all your work on this!
