### ISSUE TITLE
name token missing ater multiline type

### ISSUE THREAD

**Issue by syavorsky** [syavorsky/comment-parser#113]
Appears as reported at gajus/eslint-plugin-jsdoc#669
```
      /** Multi-line typedef for an options object type.
       *
       * @typedef {{
       *   prop: number
       * }} MyOptions
       */
```

**Comment by syavorsky** [comment]
fixed in `comment-parser@1.1.1`

**Comment by jaydenseric** [comment]
@syavorsky can we please deploy v1.1.1 to the playground?

<img width="671" alt="Screen Shot 2021-01-19 at 11 55 52 am" src="https://user-images.githubusercontent.com/1754873/104974919-69dced00-5a4d-11eb-962d-e28e36e51c41.png">

**Comment by syavorsky** [comment]
good point, fixed
