### ISSUE TITLE
Tokenizers index file has no exports

### ISSUE THREAD

**Issue by jaydenseric** [syavorsky/comment-parser#116]
The tokenizers index file has no exports:

https://unpkg.com/browse/comment-parser@1.1.1/lib/parser/tokenizers/index.js

Ideally, the tokenizers would be available as named exports in this file. Otherwise, the file is redundant and should be deleted to reduce the install size of the `comment-parser` package.

Most people use all the tokenizers, so it's not wasteful from a memory footprint / bundle size perspective to retrieve them from an index file vs deep require paths.

**Comment by syavorsky** [comment]
right, you can find tokenizers exposed at [top-level](https://unpkg.com/browse/comment-parser@1.1.1/lib/index.js), 

```js
const {tokenizers} = require('comment-parser/lib')
```
or require them separately

```js
const {default: tag} = require('comment-parser/lib/parser/tokenizers/tag')
const {default: type} = require('comment-parser/lib/parser/tokenizers/type')
const {default: name} = require('comment-parser/lib/parser/tokenizers/name')
const {default: description} = require('comment-parser/lib/parser/tokenizers/description')
```

**Comment by jaydenseric** [comment]
Thanks for the explanation, although this issue was not a question. It's a bug report that you have an empty/redundant published index file, and a feature request to populate the file.

**Comment by syavorsky** [comment]
tokenizers are available for importing from `comment-parser/lib/[index]` as mentioned above. Alternatively, if you have concerns with evaluating unused code, same entities are available from the separate single-module files. Other files were not designed for serving imports and are rather internal.
