### ISSUE TITLE
Idea: Package for exporting an ESLint parser?

### ISSUE THREAD

**Issue by brettz9** [syavorsky/comment-parser#117]
What do you think of the idea of exposing a parser that can be used by ESLint (maybe in a separate project): https://eslint.org/docs/developer-guide/working-with-custom-parsers . One might conceivably have a parser which enhanced ESLint's default `ESTree` (for regular JavaScript), one which enhanced or worked with `babel-eslint` (for experimental features), and one which worked with `@typescript-eslint/parser`.

It has the disadvantage that users would need to opt in to add a `parser` property in their ESLint config to enable it. IIRC, the estree folks weren't interested in adding parsed comments to the AST, esp. since jsdoc-form comments is not a formal part of JavaScript, so it probably wouldn't be successful to get ESLint to offer this by default. However, an advantage of opting in to such a parser would be that it would facilitate making jsdoc rules.

This is not a strong need from my end, especially as we already have many rules in `eslint-plugin-jsdoc` even without comment AST integrated into ESLint's default AST parser and this might not be that much more helpful for users than just iterating the JSON, but thought I'd bring up the idea.

Basically, the advantage would be that the [esquery](https://github.com/estools/esquery/) expressions that such a parser could facilitate (e.g., `Comment > Tag[name="param"]`), could be [used in ESLint rule creation](https://eslint.org/docs/developer-guide/selectors#listening-for-selectors-in-rules) or one could use them with the [`no-restricted-syntax`](https://eslint.org/docs/rules/no-restricted-syntax) rule to prevent features. And the likes of our `eslint-plugin-jsdoc` could perhaps check such selectors for other purposes, e.g., to add additional constraints on a specific rule.

Btw, y'all might be interested in tsdoc if you haven't come across it, which is a standard for (TypeScript-flavored) jsdoc AST: https://tsdoc.org/pages/spec/overview/ (though the spec section doesn't offer much now). I don't think it would replace comment-parser, since, for example, its [playground](https://microsoft.github.io/tsdoc/) lists any `@param` with type as "nonstandard" (though it does at least parse the type text), and I'm not sure one would trust the project wouldn't give up on plain JS users, but I did find it interesting. Maybe the proposed package could export an alternative parser which used their AST.

**Comment by syavorsky** [comment]
This indeed sounds like a good opportunity for applying the parser. But code tooling is not my field of expertise, and I wouldn't find enough time and passion for drilling into it. You are making a good point that it could evolve as a different module, which I would suggest either for anything besides basic parsing. I will keep making comment-parser more flexible and configurable though for backing other tools

**Comment by brettz9** [comment]
FWIW, I've created such an (experimental) package: https://github.com/es-joy/jsdoc-eslint-parser

Also expecting to update `eslint-plugin-jsdoc` shortly with a compromise solution which avoids the need for a separate parser, but requires a `comment` selector to narrow down the comment AST on top of a given node rather than allowing AST which merges comment AST anywhere within the expression (one can, in theory, use the parser above to do that, but it has not been well tested).

**Comment by syavorsky** [comment]
Getting 404 for the referred repo. As far as I understood from the comment, it does something like what the #99 was suggesting and more. I didn't quite get either it replaces the `comment-parser` or runs on top, unfortunately not familiar enough with AST to get all the written above.

**Comment by brettz9** [comment]
Re: 404, whoops, fixed now. 

Right, it does what #99 was suggesting, though if one wishes the programmatic functionality of converting to such AST, rather than using https://github.com/es-joy/jsdoc-eslint-parser (which is instead for users to add as their ESLint config `parser`), one can just use its dependency to do that: https://github.com/es-joy/jsdoccomment , making use of the `commentParserToESTree` method (this currently automatically uses `jsdocttypeparser` for type parsing; I'd accept a PR for other type parsers, but hopefully we can eventually standardize on one). One will also probably need `jsdocVisitorKeys` and `jsdocTypeVisitorKeys` so that traversers, etc., know what properties to check for child Nodes.

As far as whether it replaces `comment-parser`, the `jsddoccomment` package has a `parseComment` method which, while building on `comment-parser`, could be used to replace it--to work as a JSDoc-specific rather than JSDoc-like utility (I extracted that out of `eslint-plugin-jsdoc`). The `jsdoc-eslint-parser` parser doesn't require `comment-parser` of its ESLint users though it indirectly depends on `comment-parser`.

**Comment by brettz9** [comment]
Feel free to ask questions about it as you like.

We also have our jsdoc server where people can chat through questions. Feel free to join and apologies if I haven't extended an invite previously; invite expires in 7 days: https://discord.gg/224AQWCn

**Comment by brettz9** [comment]
And those interested in the potential `eslint-plugin-jsdoc` functionality can watch https://github.com/gajus/eslint-plugin-jsdoc/pull/723 .

**Comment by syavorsky** [comment]
cool, sounds like you know where you taking it

**Comment by brettz9** [comment]
Funny you should say that...

I do generally have an idea where to take it with `eslint-plugin-jsdoc`.

But it gets more murky--though I think extremely exciting in potential--to take these `eslint-plugin-jsdoc` features to work in conjunction with the ability to compile an adequately specified JS+JSDoc into WebAssembly for native performance.

With the ability now for our JSDoc ESLint  plugin to let people know if say a `@type` should be added above a particular structure (e.g., the enforcement of all functions having parameters and third party types might not be enough in all cases for static compilation to be clear without an explicit `@type`), and with the plugin already supporting indication of preferred types like say "UnsignedShortInt", "Float", etc. and such over "number", per the discussion at https://github.com/AssemblyScript/assemblyscript/issues/1837 , if a parser is not designed specifically for a robust form of JavaScript + JSDoc (what I'm calling JJ) is that, if not having a compiler that can directly compile to WebAssembly, we might use the likes of https://github.com/esmbly/esmbly/blob/master/docs/using-the-jsdoc-transformer.md to convert it to TypeScript and then to WebAssembly.

But this is well above my current pay grade, so I'm sure hoping that someone will look into allowing the web the awesome ability to get near-native performance! As mentioned in that issue, I would even think browsers could standardize on such a JS dialect (which is syntactically just a subset), e.g., by allowing for a directive to trigger the static type analysis mode.
