### ISSUE TITLE
Align transformer adding extra spaces on the end of some lines

### ISSUE THREAD

**Issue by renatho** [syavorsky/comment-parser#119]
I found and issue in the align transformer in some cases.

```js
/**
 * Description may go
 * over multiple lines followed by @tags
 * @param {string} name
 * @param {any} value the value parameter
 */
```

It's adding 2 spaces after the `name`, probably to align with the `value` description. But since we don't have description after the `name`, we could remove that spaces.

Maybe we could trim the extra spaces from the end of the lines?

**Comment by syavorsky** [comment]
I see. Yeah, you are right about the cause. Will have the fix soon.

**Comment by syavorsky** [comment]
should be fixed in `master` now, will publish along with other fixes

**Comment by syavorsky** [comment]
fixed in `comment-parser@1.1.2`

**Comment by brettz9** [comment]
Looks to be working, as I've pushed to `master` for `eslint-plugin-jsdoc` a version dropping reliance on a kludge @renatho added to overcome this, and it seems to be working fine.

**Comment by syavorsky** [comment]
Great, glad it works

**Comment by renatho** [comment]
Thank you, @syavorsky! It seems to be working for me too!
And thank you @brettz9, for update the workaround! =)
