### ISSUE TITLE
Align transformer not aligning correctly whitespace between "*" and the tag

### ISSUE THREAD

**Issue by renatho** [syavorsky/comment-parser#120]
When we try to align the following comment, it keeps the whole whitespace between the "*" and the "@param".

```
/**
 * Description may go
 * over multiple lines followed by @tags
 *        @param {string} name the name parameter
 * @param {any} value the value parameter
 */
```

**Comment by syavorsky** [comment]
Thanks for heads up, I will dig into this

**Comment by syavorsky** [comment]
should be fixed in `master` now, will publish along with other fixes

**Comment by syavorsky** [comment]
fixed in `comment-parser@1.1.2`

**Comment by brettz9** [comment]
Looks to be working, as I've pushed to `master` for `eslint-plugin-jsdoc` a version dropping reliance on a kludge @renatho added to overcome this, and it seems to be working fine. Thank you very much!

**Comment by syavorsky** [comment]
Cool, thanks for update

**Comment by renatho** [comment]
Thank you, @syavorsky! It seems to be working for me too!
And thank you @brettz9, for update the workaround! =)
