### ISSUE TITLE
Support `/** */`

### ISSUE THREAD

**Issue by brettz9** [syavorsky/comment-parser#128]
Not a useful scenario, admittedly, but I think `/** */` technically is valid jsdoc but is just getting an empty array without tokens. Trying to ensure covering all bases re: edge cases. It works with a tag, however.

**Comment by syavorsky** [comment]
From my quick check in different IDEs it is expectedly treated as never closed comment until the next valid */. I would keep it as baseline and wouldn't try to recover

**Comment by brettz9** [comment]
Sorry, not sure I understand what you mean by "treated as never closed comment until the next valid `*/`".

Of course `/** */` is a valid "multiline"-style comment but I think with a whitespace after two asterisks, it is also valid jsdoc.

And sorry but I am unclear what you are seeing in IDEs here... If you mean it isn't highlighting tags (as in Atom currently), I think that is a defect too (and your parser does support adding tokens when there is a tag anyways), but I'm speaking here of no tags.

**Comment by syavorsky** [comment]
Yes, not highlighted, rejected by compilers and runtimes as not existing code. Tried it in idea, vscode and vim. Sounds like Atom is also not happy with it. Unless I missing the point, I was talking about something like this:

```js
/** * /
alert(1)
/** */
alert(2)
```
First comment block goes until the next closest closing marker. Is this the case you are proposing to recover by still recognizing two blocks?

**Comment by brettz9** [comment]
Oh, no, I mean your second case. Where there is no space between `*/` at the end. Even this is rejected.

**Comment by brettz9** [comment]
To be clear, I mean `/** */` is not treated as jsdoc. It doesn't throw or anything, but has no tokens, despite this being a valid comment and valid jsdoc.

E.g.:

```js
/** */
function a () {}
```

**Comment by syavorsky** [comment]
sorry, "tomorrow" got pushed to sometime later, still swamped with  a work
