### ISSUE TITLE
Re-exporting

### ISSUE THREAD

**Issue by brettz9** [syavorsky/comment-parser#136]
As a follow-up to #135, it turns out even the simpler exports are not working in the older Node versions, so I would like to ask after all whether these could be added to the exports (which I've confirmed are not being exported):

- From `comment-parser/util`: `rewireSpecs`, `rewireSource`, `seedBlock`, and `seedTokens`

**Comment by brettz9** [comment]
For now, I've copied your latest `esm` code into `@es-joy/jsdoccomment`, a package that `eslint-plugin-jsdoc` imports. It'd still be nice to ensure we're accessing the latest code, but if you don't want to re-export, I can close. Thanks!

**Comment by syavorsky** [comment]
went out in `comment-parser@1.2.2`

**Comment by brettz9** [comment]
Thanks, but at least in Git, the previous merge for the `main` fix was not included in tag v1.2.2.

**Comment by syavorsky** [comment]
aaaah, you are right, I messed up and published from the wrong branch

just pushed `comment-parser@1.2.3`
