### ISSUE TITLE
define custom tags

### ISSUE THREAD

**Issue by nnaydenow** [syavorsky/comment-parser#166]
Hi @syavorsky,

Is it possible to define custom tags or is it documented anywhere how to do it?

For example
```js
/**
* My description
* @my-tag Description
* @my-second-tag sample-name Description
```

To result into:
```js
[
    {
        type: "my-tag",
        description: "Description"
        // here without name and other properties...
    },
    {
        type: "my-second-tag",
        name: "sample-name",
        description: "Description"
    }
]
```

**Comment by syavorsky** [comment]
The parser is tag agnostic, you can use any tags you like and the have a validation layer on top

**Comment by nnaydenow** [comment]
Is there any documentation how to write that validation layer?

**Comment by syavorsky** [comment]
I mean the parser output above is what you get as an input for you validator. It is completely up to you how you implement it.
