### ISSUE TITLE
Missing Typescript declaration for file function

### ISSUE THREAD

**Issue by Kim-Andersen** [syavorsky/comment-parser#77]
Maybe I'm missing something, but I think the library is missing a Typescript type declaration for the "file" function (passing a file path to be parsed)?

**Comment by syavorsky** [comment]
`1.0` went to the `master` and is current stable version. The lib is rewritten in TS, so missing definitions should not be the issue now. File streaming parser is not added yet, but I hope you should be fine using `parse(wholeFileSource)` for now
