### ISSUE TITLE
Preserve multiline asterisk info

### ISSUE THREAD

**Issue by brettz9** [syavorsky/comment-parser#79]
While it may not be of interest to all, knowing which lines had asterisks can be useful, especially for stringification, to ensure fidelity to the original (as with eslint fixes based on a parsed-then-modified-then-stringified string).

Would you be open to a PR which exposed this, e.g., by mapping those line numbers with or without an asterisk?

**Comment by syavorsky** [comment]
`1.0` went to the `master` and is current stable version now. New output format should have this info in `Block[].source[].tokens`
