### ISSUE TITLE
Parses @return incorrectly

### ISSUE THREAD

**Issue by jaydenseric** [syavorsky/comment-parser#82]
The `@returns`/`@return` tag is not supposed to have a name:

https://jsdoc.app/tags-returns.html

E.g. this is valid:

```
@return {*} Description.
```

And this is not:

```
@return {*} foo Description.
```

Yet, the tests for `comment-parser` enforce a name:

https://github.com/syavorsky/comment-parser/blob/58aa3e2e84171119952049af423cc1fcf509cc57/tests/parse.spec.js#L1143

In fact, parsing `@return {*} Description.` gives this result:

```json
[
  {
    "tags": [
      {
        "tag": "return",
        "type": "*",
        "name": "Description.",
        "optional": false,
        "description": "",
        "line": 1,
        "source": "@return {*} Description."
      }
    ],
    "line": 0,
    "description": "",
    "source": "@return {*} Description."
  }
]
```

The `return` tag `description` is incorrectly an empty string, while the `name` is incorrectly the description text.

Parsing `@return {*} - Description.` gives this result:

```json
[
  {
    "tags": [
      {
        "tag": "return",
        "type": "*",
        "name": "-",
        "optional": false,
        "description": "Description.",
        "line": 1,
        "source": "@return {*} - Description."
      }
    ],
    "line": 0,
    "description": "",
    "source": "@return {*} - Description."
  }
]
```

It incorrectly thinks the `name` is `"-"`.

This is a pretty critical bug that blocks me from migrating [`jsdoc-md`](https://github.com/jaydenseric/jsdoc-md) from [`doctrine`](https://github.com/eslint/doctrine), I'm not sure the best way to deal with it until it's fixed here.

**Comment by brettz9** [comment]
This project's stated aim is at being for jsdoc-like--it is not aware of jsdoc's own semantics. You can add your own custom parser as per https://github.com/syavorsky/comment-parser#parsers-parser-custom-parsers , e.g., for `parse_name1`, instead check `data.tag` for `return` and `returns` and return `null`. We use this approach in `eslint-plugin-jsdoc`.

**Comment by jaydenseric** [comment]
Thanks for the clarification, I'll link to what I came up with in the end once I push it up. First I have to resolve a final hurdle regarding how default value quotes are handled, which I'll raise a seperate issue for shortly.
