### ISSUE TITLE
Default value quotes should not be stripped

### ISSUE THREAD

**Issue by jaydenseric** [syavorsky/comment-parser#83]
At the moment, parsing strips the quotes wrapping default values:

https://github.com/syavorsky/comment-parser/blob/58aa3e2e84171119952049af423cc1fcf509cc57/tests/parse.spec.js#L589

This is problematic, because it makes it impossible to tell the difference between a string literal default value, or a namepath reference.

E.g.

```js
/**
 * The description.
 * @kind constant
 * @name FOO
 * @type {string}
 */
const FOO = 'FOO'

/**
 * @kind function
 * @name bar
 * @param {string} [foo=FOO] The description.
 */
function bar(foo = FOO) {}
```

Vs:

```js
/**
 * The description.
 * @kind function
 * @name bar
 * @param {string} [foo='FOO'] The description.
 */
function bar(foo = 'FOO') {}
```

I need to be able to tell the difference in [`jsdoc-md`](https://github.com/jaydenseric/jsdoc-md), so that for default values I can create a link around a namepath reference vs an inline code display of a string literal.

**Comment by syavorsky** [comment]
`+ comment-parser@0.7.5`
