### ISSUE TITLE
make alignFormatter configurable

### ISSUE THREAD

**Issue by syavorsky** [syavorsky/comment-parser#96]
as per conversation in #93:
- export [alignFormatter](https://github.com/syavorsky/comment-parser/blob/1.0/src/stringifier.ts#L46) and make it configurable
- add the `indent:number` option

**Comment by syavorsky** [comment]
@brettz9 @renatho I ended up splitting the transformation logic from stringifying. So at the end stringifier is just concatenating tokens together, but before that you can process them as you like. Check out [this example](https://syavorsky.github.io/comment-parser/#stringify-formatting). I hope, tweaking the formatting should be easy enough with custom hooks, see what [align](https://github.com/syavorsky/comment-parser/blob/1.0/src/transforms/align.ts) and [indent](https://github.com/syavorsky/comment-parser/blob/1.0/src/transforms/indent.ts) do

**Comment by brettz9** [comment]
Thanks for the heads up, and happy to see these transforms available. Hopefully the approach won't add too much to execution time. I'm unfortunately not in a position to try them out myself these days, though hopefully I can by the time you feel it is ready for a release. Thanks much!

**Comment by syavorsky** [comment]
@brettz9 no probs, tweaking transforms as needed later should not be a problem

**Comment by renatho** [comment]
Thank you @syavorsky!
Nice approach about the `transforms` 👏 I think it'll be easy to implement and it'll also create new possibilities for the lib! \o/

**Comment by syavorsky** [comment]
@renatho no prob, I should thank you indeed for kicking off the whole 1.0 refactoring :)
